- name: Telemetry Streaming (TS) playbook
  hosts: tag_Role_bigip
  connection: local
  vars_files: "{{ setupfile }}"

  tasks:
    - name: Set connection provider for BIG-IP tasks
      set_fact:
        provider:
          server: "{{ public_dns_name }}"
          server_port: 8443
          user: "{{ bigip.admin_user }}"
          password: "{{ bigip.admin_password }}"
          validate_certs: false

    ### Only needed in case of cloudwatch ###
    - name: Fetch AWS credentials (needed for cloudwatch)
      shell: aws configure get aws_access_key_id
      register: aws_access_key_id
      changed_when: false
      tags: cloudwatch

    ### Only needed in case of cloudwatch ###
    - name: Fetch AWS credentials (needed for cloudwatch)
      shell: aws configure get aws_secret_access_key
      register: aws_secret_access_key
      changed_when: false
      tags: cloudwatch

    ### Only needed in case of cloudwatch ###
    - name: Register AWS credentials as facts
      set_fact: 
        aws_access_key_id={{ aws_access_key_id.stdout }}
        aws_secret_access_key={{ aws_secret_access_key.stdout }}
      tags: cloudwatch

    - name: Wait for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 600
        provider: "{{ provider }}"
      tags: cloudwatch

    ####################################
    # Perform TS Deployment Cloudwatch #
    ####################################
    - name: Process jinja template and store result for artifact storage (cloudwatch json blob for TS)
      template:
        src: templates/ts/cloudwatch.json.j2
        dest: "{{ outputfolder }}/ts_cloudwatch.json"
        mode: 0644
      tags: cloudwatch
  
    - name: Perform TS registration
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/ts_cloudwatch.json"
        atc_delay: 10
        atc_retries: 5
      tags: cloudwatch

    - name: Store result of TS registration for artifact storage (cloudwatch json blob for TS)
      copy:
        content: |
          {{ (atc_TS_status.json is defined) | ternary(atc_TS_status.json | to_nice_json(indent=2), atc_TS_status.content) }}
        dest: "{{ outputfolder }}/ts_cloudwatch_result.json"
      tags: cloudwatch

    ##################################
    # Perform TS Deployment Graphite #
    ##################################
    - name:  Get the private and public ip of the host running graphite/grafana/statsd
      set_fact:
        grafana_private_ip: "{{ groups[group_name] | map('extract', hostvars, 'private_ip_address') | list | first }}" 
        graphite_private_ip: "{{ groups[group_name] | map('extract', hostvars, 'private_ip_address') | list | first }}" 
        statsd_private_ip: "{{ groups[group_name] | map('extract', hostvars, 'private_ip_address') | list | first }}" 
        grafana_public_ip: "{{ groups[group_name] | map('extract', hostvars, 'public_ip_address') | list | first }}" 
        graphite_public_ip: "{{ groups[group_name] | map('extract', hostvars, 'public_ip_address') | list | first }}" 
        statsd_public_ip: "{{ groups[group_name] | map('extract', hostvars, 'public_ip_address') | list | first }}" 
      vars:
        group_name: "tag_Role_graphite_grafana"

    ### Graphite Specific ###
    - name: Process jinja template and store result for artifact storage (graphite json blob for TS)
      template:
        src: templates/ts/graphite.json.j2
        dest: "{{ outputfolder }}/ts_graphite.json"
        mode: 0644
      tags: graphite_grafana
  
     ### Graphite Specific ###
    - name: Perform TS registration
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/ts_graphite.json"
        atc_delay: 10
        atc_retries: 5
      tags: graphite_grafana

    ### Graphite Specific ###
    - name: Store result of TS registration for artifact storage (graphite json blob for TS)
      copy:
        content: |
          {{ (atc_TS_status.json is defined) | ternary(atc_TS_status.json | to_nice_json(indent=2), atc_TS_status.content) }}
        dest: "{{ outputfolder }}/ts_graphite_result.json"
      tags: graphite_grafana

    ### Statsd Specific ###
    - name: Process jinja template and store result for artifact storage (statsd json blob for TS)
      template:
        src: templates/ts/statsd.json.j2
        dest: "{{ outputfolder }}/ts_statsd.json"
        mode: 0644
      tags: statsd_grafana

    ### Statds Specific ###
    - name: Perform TS registration
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/ts_statsd.json"
        atc_delay: 10
        atc_retries: 5
      tags: statsd_grafana

    ### Statds Specific ###
    - name: Store result of TS registration for artifact storage (statsd json blob for TS)
      copy:
        content: |
          {{ (atc_TS_status.json is defined) | ternary(atc_TS_status.json | to_nice_json(indent=2), atc_TS_status.content) }}
        dest: "{{ outputfolder }}/ts_statsd_result.json"
      tags: statsd_grafana

    ### Grafana DataSource Specific
    - name: Process jinja template and store result for artifact storage
      template:
        src: templates/grafana/datasource_graphite.json.j2
        dest: "{{ outputfolder }}/grafana_datasource_graphite.json"
        mode: 0644
      tags: graphite_grafana

    ### Grafana DataSource Specific
    - name: Check of graphite datasource for grafana already exists
      uri:
        url: "http://{{ grafana_public_ip }}:3000/api/datasources"
        user: admin
        password: admin
        method: GET
        force_basic_auth: yes
        status_code: 200
      register: get_result
      until: get_result.status == 200
      retries: 30
      delay: 10
      tags: graphite_grafana

    ### Grafana Datasource Specific
    - name: Add graphite datasource into grafana
      uri:
        url: "http://{{ grafana_public_ip }}:3000/api/datasources"
        user: admin
        password: admin
        method: POST
        body: "{{ lookup('file','{{ outputfolder }}/grafana_datasource_graphite.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: post_result
      until: post_result.status == 200
      retries: 30
      delay: 10
      when: >
        (get_result.json is defined and get_result.json | length == 0) or get_result.json is undefined
      tags: graphite_grafana

    ### Grafana Dashboard Specific
    - name: Add graphite statsd dashboard into grafana
      uri:
        url: "http://{{ grafana_public_ip }}:3000/api/dashboards/db"
        user: admin
        password: admin
        method: POST
        body: >
          {
            "dashboard": {{ lookup('file','templates/grafana//statsd_dashboard.json') }},
            "folderId": 0,
            "overwrite": false
          }
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: post_result
      until: post_result.status == 200
      retries: 30
      delay: 10
      tags: graphite_grafana

    - name: Print the URL for Grafana / Graphite / Statsd
      debug:
        msg: >
          Verify if metrics and/or events are arriving at the following admin UI's
            > Grafana UI   : http://{{ grafana_public_ip }}:3000
            > Graphite UI  : http://{{ graphite_public_ip }}:80
            > Statsd Admin : echo "gauges" | nc 34.244.144.97 8126

    #############################
    # Perform TS Deployment ELK #
    #############################
    - name:  Get the private and public ip of the host running elk (elasticsearch, logstash, kibana)
      set_fact:
        elk_private_ip: "{{ groups[group_name] | map('extract', hostvars, 'private_ip_address') | list | first }}" 
        elk_public_ip: "{{ groups[group_name] | map('extract', hostvars, 'public_ip_address') | list | first }}" 
      vars:
        group_name: "tag_Role_elk"

    - name: Process jinja template and store result for artifact storage (elk json blob for TS)
      template:
        src: templates/ts/elk.json.j2
        dest: "{{ outputfolder }}/ts_elk.json"
        mode: 0644
      tags: elk
  
    - name: Perform TS registration
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/ts_elk.json"
        atc_delay: 10
        atc_retries: 5
      tags: elk

    - name: Store result of TS registration for artifact storage (elk json blob for TS)
      copy:
        content: |
          {{ (atc_TS_status.json is defined) | ternary(atc_TS_status.json | to_nice_json(indent=2), atc_TS_status.content) }}
        dest: "{{ outputfolder }}/ts_elk_result.json"
      tags: elk

    - name: Print the URL for ELK (Elasticsearch, Logstash and Kibana)
      debug:
        msg: >
          Verify if metrics and/or events are arriving at the following admin UI's
          > Elasticsearch UI  : http://{{ elk_public_ip }}:9200
          > ES Cluster Health : http://{{ elk_public_ip }}:9200/_cluster/health
          > ES Indices        : http://{{ elk_public_ip }}:9200/_cat/indices
          > Kibana UI         : http://{{ elk_public_ip }}:5601
  
  ####################################
  # Manual verification on BIG-IP(s) #
  ####################################
  post_tasks:
    - name: Final result verification on BIG-IP 
      debug:
        msg: >
          Verify on BIG-IQ(s) if your desired results was achieved
            > Admin UI   : https://{{ public_dns_name }}:8443
            > REST URI   : https://{{ public_dns_name }}:8443/mgmt/shared/telemetry/declare
            > DOCS URL   : https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest
            > SCHEMA REF : https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/schema-reference.html
            > GITHUB SRC : https://github.com/F5Networks/f5-telemetry-streaming
